# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: SSH-SoC 2024
email: sshsocworkshoporganization@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  SSH-SoC - Safety and Security in Heterogeneous Open System-on-Chip Platforms
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ssh-soc-workshop.github.io" # the base hostname & protocol for your site, e.g. http://example.com
domain: "ssh-soc-workshop.github.io"

# Build settings
theme: null
plugins:
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Collections settings
collections_dir: collections
collections:
  pastevents:
    output: false
  organizers:
    output: false
  speakers:
    output: false
  contributions:  
    output: true

# Sets the collections path
defaults:
  - scope:
      path: "collections/_organizers/chair"
    values:
      organizer_type: "chair"
  - scope:
      path: "collections/_organizers/sc"
    values:
      organizer_type: "sc"
  - scope:
      path: "collections/_organizers/tpc"
    values:
      organizer_type: "tpc"
  - scope:
      path: "collections/_organizers/web"
    values:
      organizer_type: "web"
  - scope:
      path: "collections/_organizers/publicity"
    values:
      organizer_type: "publicity"

exclude:
  - "robots.txt"
